### ISSUE TITLE
Mastercode for SLPM_654.95

### ISSUE THREAD

**Issue by Slider2k** [PS2-Widescreen/Bare-Mastercodes-bin#1]
- [x] Tested

```
"Monster Hunter /ID SLPM_654.95"
//ELF CRC=CF1A62C0

Mastercode
901B7F70 0C0676DC
```
[Source](https://forum.gamehacking.org/forum/video-game-hacking-and-development/retro-hacking/5491-ps2-monster-hunter-hp-display-hack-multiversion)

**Comment by israpps** [comment]
was added on https://github.com/PS2-Widescreen/Bare-Mastercodes-bin/commit/a5dbf4ff4d66695141c2465455ee01e77a0381c9
